<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Registration Details</title>
    <style>
        body { 
            font-family: DejaVu Sans, sans-serif;
            color: #333;
            margin-top: 130px;
            margin-bottom: 70px;
            margin-left: 40px;
            margin-right: 40px;
        }
        
        .section-title {
            background: #1565c0;
            color: #ffffff;
            padding: 12px 20px;
            font-size: 16px;
            font-weight: bold;
            margin: 20px 0 0 0;
        }
        
        .data-table { 
            width: 100%; 
            border-collapse: collapse;
            margin-bottom: 20px;
            border: 2px solid #e0e0e0;
        }
        
        .data-table th { 
            background-color: #fafafa;
            padding: 10px 15px;
            text-align: left;
            font-weight: bold;
            color: #c62828;
            width: 35%;
            font-size: 11px;
            text-transform: uppercase;
            border: 1px solid #e0e0e0;
        }
        
        .data-table td { 
            padding: 10px 15px;
            text-align: left;
            color: #424242;
            font-size: 11px;
            line-height: 1.5;
            word-wrap: break-word;
            border: 1px solid #e0e0e0;
        }
        
        .pdf-footer {
            background: #f5f5f5;
            border-top: 3px solid #c62828;
            padding: 15px 20px;
            text-align: center;
            margin: 30px -20px -20px -20px;
            font-size: 10px;
            color: #757575;
        }
        
        .footer-brand {
            color: #c62828;
            font-weight: bold;
            font-size: 11px;
        }
        
        .document-info {
            margin: 20px 0;
            padding: 12px;
            background: #f9f9f9;
            border-left: 4px solid #1565c0;
            font-size: 9px;
            color: #666;
            line-height: 1.4;
        }
    </style>
</head>
<body>
    <div class="section-title">User Information</div>
    <table class="data-table">
        @foreach($registration->toArray() as $key => $value)
            @if($key !== 'password')
            <tr>
                <th>{{ ucfirst(str_replace('_', ' ', $key)) }}</th>
                <td>{{ in_array($key, ['email_orders', 'phone_orders', 'telephone_orders', 'whatsapp_orders', 'agree_terms']) ? ($value ? 'Yes' : 'No') : $value }}</td>
            </tr>
            @endif
        @endforeach
    </table>
    
    <!-- <div class="document-info">
        <strong>Document Information:</strong> This is an official registration document generated by Smartify Tech. 
        All information provided is confidential and should be handled according to data protection regulations.
    </div> -->
</body>
</html>
